language: python

matrix:
    include:
        - python: 3.5
        - python: 3.6
        - python: 3.7
          dist: xenial
          sudo: true

# GitHub branch
branches:
  only:
    - master

# prep installation
before_install:
  - sudo apt-get update
  - sudo updatedb
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda info -a

# install package and dependencies
install:
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install cmake -y
  - pip install coverage nose pytest pytest-cov pytest-pep8
  - pip install numpy modopt sf_tools
  - pip install git+https://github.com/CEA-COSMIC/pysap
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install coveralls; fi

# run unit tests
script:
  - python -c "import pysap"
  - python setup.py test

# run coverage tests
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then coveralls; fi

# notification settings
notification:
  email: false
