language: python

matrix:
    include:
        - python: 3.5
        - python: 3.6
        - python: 3.7
          dist: xenial
          sudo: true

addons:
  apt:
    packages:
      - cmake

# GitHub branch
branches:
  only:
    - master

# prep installation 
before_istall:
  - if [ $TRAVIS_PYTHON_VERSION == "3.6" ]; then
      export CPLUS_INCLUDE_PATH=/opt/python/3.6.3/include/python3.6m;
    fi
  - if [ $TRAVIS_PYTHON_VERSION == "3.7" ]; then
      export CPLUS_INCLUDE_PATH=/opt/python/3.7.1/include/python3.7m;
    fi

# install package and dependencies
install:
  - pip install coverage nose pytest pytest-cov pytest-pep8
  - pip install numpy modopt sf_tools
  - pip install git+https://github.com/CEA-COSMIC/pysap
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install coveralls; fi

# run unit tests
script:
  - python -c "import pysap"
  - python setup.py test

# run coverage tests
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then coveralls; fi

# notification settings
notification:
  email: false
